# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DojoNinjas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
