# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAuthors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=' '),
        ),
    ]
